fixtures:
    repositories:
        stdlib:  "git://github.com/puppetlabs/puppetlabs-stdlib.git"
        apache:
          repo: "git://github.com/puppetlabs/puppetlabs-apache.git"
          ref: '0.8.0'
        puppetdb: "git://github.com/puppetlabs/puppetlabs-puppetdb.git"
        inifile: "git://github.com/cprice-puppet/puppetlabs-inifile.git"
        firewall: "git://github.com/puppetlabs/puppetlabs-firewall.git"
        concat: "git://github.com/ripienaar/puppet-concat.git"
        apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    symlinks:
        puppet: "#{source_dir}"
